#!/bin/sh

[ "${PLENV_ROOT}" ] || PLENV_ROOT="${HOME}/.plenv"

oldest=5.8
suffix=

args=`getopt o:s: $*`
if [ $? -ne 0 ]
then
	echo 'Usage: [ -o oldest ] [ -s suffix ] -- [ extra plenv-install args ]'
	exit 2
fi
set -- $args
while [ $# -ne 0 ]
do
	case "$1"
	in
		-o)
			oldest="$2"; shift; shift;;
		-s)
			suffix="$2"; shift; shift;;
		--)
			shift; break;;
	esac
done

if ! perl -Mversion -e "version->parse('v$oldest')"; then
	echo "Invalid oldest version ($oldest), try -o 5.8" >&2
	exit 2
fi

perl_name_to_version() {
	local _n=$1
	local version
	eval $( PLENV_VERSION=$_n plenv exec perl -V:version 2>/dev/null )
	echo $version
}

remove_perl() {
	local _n=$1

	local prefix=$( PLENV_VERSION=$_n plenv prefix 2>/dev/null )
	[ "$prefix" -a -d "$prefix" ] || return

	echo "Removing $( perl_name_to_version $_n ) was $_n"
	rm -r "$prefix"
}

install_perl() {
	local _v=$1; shift
	local _n=$2; shift

	local current=$( perl_name_to_version $_n )
	if [ "$current" ]; then
		if [ "$current" != "$_v" ]; then
			remove_perl $_n
		else
			return
		fi
	fi

	plenv install $_v --as=$_n "$@"
}

plenv install --list | grep '^ 5\.' | grep -v '^ 5.00' | tr '.' ' ' | (
	last=""
	dev=""

	while read m n p; do
		version="$m.$n.$p"
		name="$m.$n"
		args=""

		[ "$oldest" ] &&
		    perl -Mversion -e \
		    "exit( version->parse('v$oldest') > 'v${version%-*}' )" ||
		    break # don't need that old of perl

		if [ $(( $n % 2 )) -ne 0 ]; then
			[ "$last" -a "$dev" != "$name" ] && remove_perl $name
			dev=$name
			args="-Dusedevel"
			[ "$last" ] && continue
		fi

		if [ "$name" != "$last" ]; then
			install_perl $version $name$suffix "$@" $args
			if [ -e "${PLENV_ROOT}/extra-modules" ]; then
			    PLENV_VERSION=$name$suffix plenv install-cpanm
			    PLENV_VERSION=$name$suffix plenv exec cpanm \
                                < "${PLENV_ROOT}/extra-modules"
			fi
		fi

		last=$name;
	done
)

