#!/bin/sh

if [ -z "$PLENV_ROOT" ]; then
  PLENV_ROOT="${HOME}/.plenv"
fi

extra_modules="${PLENV_ROOT}"/extra-modules

if [ ! -s "$extra_modules" ]; then
	echo "Add modules to $extra_modules" >&2
	exit 1
fi

plenv install-cpanm
plenv exec cpanm < "$extra_modules"
