#!/usr/bin/env bash
set -e

[ "${PLENV_ROOT}" ] || PLENV_ROOT=$( plenv root )

dry_run=
oldest=5.8
suffix=

set -- $( getopt no:s: "$@" )
if [ $? -ne 0 ]
then
	echo 'Usage: [-n] [ -o oldest ] [ -s suffix ] -- [ extra plenv-install args ]'
	exit 2
fi
while [ $# -ne 0 ]
do
	case "$1"
	in
		-n)
			dry_run=1; shift;;
		-o)
			oldest="$2"; shift; shift;;
		-s)
			suffix="$2"; shift; shift;;
		--)
			shift; break;;
	esac
done

if ! perl -Mversion -e "version->parse('v$oldest')"; then
	echo "Invalid oldest version ($oldest), try -o 5.8" >&2
	exit 2
fi

perl_name_to_version() {
	local _v=$1
	PLENV_VERSION=$_v plenv exec perl -V 2>/dev/null |
	PLENV_VERSION=$_v plenv exec perl -MConfig -n \
	    -e '$rc="-$1" if ( /Locally /../^\s*Built / ) && /\b(RC\d+)\b/;' \
	    -e 'END { print "$Config{version}$rc" }' 2>/dev/null || true
}

remove_perl() {
	local _n=$1

	local prefix
	prefix=$( PLENV_VERSION=$_n plenv prefix 2>/dev/null || true )

	[ "$prefix" ] && [ -d "$prefix" ] || return 0

	if [ "$dry_run" ]; then
		echo "Would remove $prefix"
		return 0
	fi

	echo "Removing $( perl_name_to_version "$_n" ) was $_n"
	rm -r "$prefix"
}

install_perl() {
	local _v=$1; shift
	local _n=$1; shift

	local current
	current=$( perl_name_to_version "$_n" )
	if [ "$current" ]; then
		if [ "$current" != "$_v" ]; then
			remove_perl "$_n"
		else
			return 0
		fi
	fi

	if [ "$dry_run" ]; then
		local extra
		[ "$*" ] && extra=" ($*)"
		echo "Would install  $_v as $_n$extra"
		return 0
	fi
	plenv install "$_v" --as="$_n" "$@"
}

install_extra_modules() {
	local _n=$1; shift
	[ -e "${PLENV_ROOT}/extra-modules" ] || return 0

	if [ "$dry_run" ]; then
		#echo "Installing cpanm and extra-modules to $_n"
		return 0
	fi

	PLENV_VERSION="$_n" plenv install-cpanm
	PLENV_VERSION="$_n" plenv exec cpanm \
	    --notest < "${PLENV_ROOT}/extra-modules"
}

plenv install --list | grep '^ 5\.' | grep -v '^ 5.00' | tr '.' ' ' | (
	last=""
	dev=""

	while read -r m n p; do
		version="$m.$n.$p"
		name="$m.$n"
		args=""

		if [ "$oldest" ]; then
		    perl -Mversion -e \
		    "exit( version->parse('v$oldest') > 'v${version%-*}' )" ||
		    break # don't need that old of perl
		fi

		if [[ $p =~ [0-9]-RC[0-9] ]]; then
			if [ "$name" = "$last" ] ||
			   [ "${version%[0-9]}" = "${last%[0-9]}" ]; then
				remove_perl "$version"
				[ "$name" = "$last" ] || last=$version
				continue
			fi
			name=$version
		fi

		if (( n % 2 != 0 )); then
			[ "$last" ] && [ "$dev" != "$name" ] && remove_perl "$name"
			dev=$name
			args="-Dusedevel"
			[ "$last" ] && continue
		fi

		if [ "$name" != "$last" ]; then
			install_perl "$version" "$name$suffix" "$@" ${args:+"${args}"}
			install_extra_modules "$name$suffix"
		fi

		last=$name;
	done
)

